name: Make Script

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    paths-ignore: # Don't trigger on files that are updated by the CI
      - "static/*.csv"
    branches:
      - main
      - master
  schedule:
    - cron:  '8 8 * * *'

jobs:
  update_csvs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python And make tickers
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - run: |
        pip3 install -r scripts/requirements.txt
        python scripts/fetch_data.py
        python scripts/make_md_file.py

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action $date"
        git add static --force
        git commit -m "Adding new files"
        git push

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - run: npm install
    - run: npm run build
    - run: npm run generate

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
    # this will trigger the node pipeline