name: Make Script

on:
  push:
    paths-ignore: # Don't trigger on files that are updated by the CI
    - "**.csv"
    - "*.csv"
    - "scripts/*.csv"
    branches:
      - master

jobs:
  update_csvs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python And make tickers
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - run: |
        pip3 install cad-tickers
        python scripts/fetch_data.py
    
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action $date"
        git add static --force
        git commit -m "Adding new files"
        git push
    # this will trigger the node pipeline