name: github pages

on:
  push:
    paths: # Trigger when csv is updated
    - "**.csv"
    - "*.csv"
    - "scripts/*.csv"
    branches:
      - master

jobs:
  build_pages:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '12'
      check-latest: true
  - run: npm install
  - run: ls static
  - run: npm run build
  - run: npm run generate

  - name: Deploy
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist