name: Updating Stock Api

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STOCK_API: ${{ secrets.STOCK_API }}

on:
  push:
    paths-ignore: # Don't trigger on files that are updated by the CI
      - "static/*.csv"
    branches:
      - main
      - master
  schedule:
    - cron:  '8 8 * * 3'

jobs:
  update_csvs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python And make tickers
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: |
        pip3 install -r scripts/requirements.txt
        python scripts/get_ticker_list.py
        git add .

    - name: Commit Changes
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action $date"
        git add static --force
        git config pull.rebase false
        git pull || true
        git commit -m "Adding new files"
        git pull || true
        git push
